### ISSUE TITLE
Tree scrolls to the beginning after doing a signal subscription

### ISSUE THREAD

**Issue by StefanBerlin** [TUB-Control/PaPI#11]
In overview.
Select a plugin and try to subscribe a signal which need a scroll down to be seen.
After clicking subscribe in context menue, the list will scroll up to the beginning.

Some research showed that this error/bug seems to be affected by the subscription event which will be put in the core queue( to be found in gui api).

**Comment by StefanBerlin** [comment]
somehow the  core queue call is responsible for that. Maybe there is some sort of focus loss.

**Comment by StefanBerlin** [comment]
not that important but the fix seems to be quit complicated

**Comment by SvKn** [comment]
This behaviour is triggered by a refresh of the overviewmenu --> is currently disabled.
Disables also live updates of parameters.

**Comment by SvKn** [comment]
Restored old ability without the described disadvantage.
Still not possible to remove a single signal in the tree of subscribers.
