### ISSUE TITLE
Plot: Down sampling feature

### ISSUE THREAD

**Issue by SvKn** [TUB-Control/PaPI#12]
Check if the following redesign of the sampling feature gives a performance boost:

Realize down sampling by saving only a subset of the receiving in the internal buffer 

INSTEAD OF

Saving of all data in the internal buffer with down sampling afterwards

Expected advantages:
Rolling plot has no longer a dependency on the data length received by the plot.
Less data written to buffer, less internal buffer.

Expected disadvantage:
Maybe more overhead in the execute phase for less data.

**Comment by StefanBerlin** [comment]
It should also be checked, if the build in pyqtgraph downsampling is stable and will bring a performance increase afterall.

**Comment by SvKn** [comment]
The build in pyqtgraph down sampling can't be used due to the use of graphic items which are drawn by the plots.
A simple down sampling method was implemented which results in a performance boost. Expected disadvantages are not appeared.
