### ISSUE TITLE
Y-Skalierung nimmt manchmal nicht die gegebenen Werte an

### ISSUE THREAD

**Issue by christianausb** [TUB-Control/PaPI#37]
[PacketFramework, Plot2] = ld_PF_addpluginAdvanced(PacketFramework, "Plot", "Angle 25.1", "(500,300)", "(0,600)", "PaPI-Tab", list(["yRange","[-0.1 2]"]));
                    [sim, PacketFramework]=ld_SendPacketInclSub(sim, PacketFramework, Signal=ang, NValues_send=1, datatype=ORTD.DATATYPE_FLOAT, SourceName="Th", Plot2, 'SourceGroup0');

Skaliert im Plot auf 0 bis 6. Der Wert "2" kommt allerdings im Plot-Plugin an.

**Comment by StefanBerlin** [comment]
Not really a bug.

 list(["yRange","[-0.1 2]"])

Range values for the plot plugin need to be float values.

[1.0 2] will not work.

[1.0 2.0] will work.
