### ISSUE TITLE
UDP_Plugin doesn't work anymore

### ISSUE THREAD

**Issue by SvKn** [TUB-Control/PaPI#60]
UDP_Plugin gets a working configuration which is forwarded to the PaPIController. Data is also sent by the PaPIBlock-Simulink-Block (seen in wireshark) but the Data aren't forwarded to plugins which have subscribed the data.

**Comment by SvKn** [comment]
Please check !

**Comment by StefanBerlin** [comment]
Checked the fix. Is valid.
Closed.
