### ISSUE TITLE
Search Bar for overview and create window

### ISSUE THREAD

**Issue by StefanBerlin** [TUB-Control/PaPI#62]
A little search field for searching plugins would be nice

**Comment by SvKn** [comment]
Please Check !

**Comment by StefanBerlin** [comment]
Improvement for usage:  add some shortcuts and set search bar active at window creation

**Comment by StefanBerlin** [comment]
Please Check shortcuts

**Comment by SvKn** [comment]
Display action shortcut in the toolbar menu if it exits

**Comment by StefanBerlin** [comment]
shortcuts are shown now.
